# Static integration guards, not a substitute for live gameplay tests.
file(READ "${SOURCE_ROOT}/modules/mod-playerbots/src/playerbot/strategy/actions/ChooseTravelTargetAction.cpp" travelActions)
foreach(action RequestTravelTargetAction RequestNamedTravelTargetAction RequestQuestTravelTargetAction)
    string(FIND "${travelActions}" "bool ${action}::Execute(Event& event)\n{\n    if (IsTravelSearchPending(*AI_VALUE(FutureDestinations*, \"future travel destinations\")))\n        return false;" pendingGuard)
    if(pendingGuard LESS 0)
        message(FATAL_ERROR "Travel request can replace a pending async future: ${action}")
    endif()
endforeach()
file(READ "${SOURCE_ROOT}/modules/mod-playerbots/src/playerbot/PlayerbotAI.cpp" travelReset)
string(FIND "${travelReset}" "target->SetStatus(TravelStatus::TRAVEL_STATUS_EXPIRED);" invalidated)
string(FIND "${travelReset}" "FutureDestinations* future = AI_VALUE" retained)
if(invalidated LESS 0 OR retained LESS invalidated)
    message(FATAL_ERROR "Travel reset must invalidate target before retaining stale future")
endif()
file(READ "${SOURCE_ROOT}/src/game/Maps/Map.cpp" map)
file(READ "${SOURCE_ROOT}/src/game/Maps/MapManager.cpp" manager)
file(READ "${SOURCE_ROOT}/src/game/World.cpp" world)
file(READ "${SOURCE_ROOT}/modules/mod-playerbots/src/playerbot/PlayerbotScripts.cpp" bots)
file(READ "${SOURCE_ROOT}/src/game/Movement/spline/MoveSplineInit.cpp" spline)
foreach(required "ScriptsProcess();" "i_data->Update(t_diff);" "UpdateScriptedEvents();"
    "eluna->OnMapUpdate(this, t_diff);" "SendObjectUpdates();" "UpdateVisibilityForRelocations();"
    "m_bLoadedGrids[gx][gy]" "IsStaggeredMapWorkDue" "GetMapWorkGeneration()")
    string(FIND "${map}" "${required}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Missing map integration: ${required}")
    endif()
endforeach()
foreach(required "sTransportMgr.Update(diff);" "sMapMgr.Update(diff);" "sBattleGroundMgr.Update(diff);"
    "sLFGMgr.Update(diff);" "sLFTMgr.Update(diff);")
    string(FIND "${world}" "${required}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Missing world gameplay hook: ${required}")
    endif()
endforeach()
string(FIND "${manager}" "runBatch(work);" firstJoin)
string(FIND "${manager}" "map->CompleteUpdate();" complete)
string(FIND "${manager}" "    SwitchPlayersInstances();" transfer)
if(firstJoin EQUAL -1 OR complete LESS firstJoin OR transfer LESS complete)
    message(FATAL_ERROR "Map owner / completion / transfer ordering changed")
endif()
foreach(forbidden "waitContinentUpdateFinishedUntil" "MarkContinentUpdateFinished")
    string(FIND "${map}${manager}" "${forbidden}" found)
    if(NOT found EQUAL -1)
        message(FATAL_ERROR "Worker-to-worker barrier reintroduced")
    endif()
endforeach()
string(REGEX MATCHALL "ai->UpdateAI\\(" aiCalls "${bots}")
list(LENGTH aiCalls aiCallCount)
if(NOT aiCallCount EQUAL 1)
    message(FATAL_ERROR "Expected one module AI dispatch path, found ${aiCallCount}")
endif()
string(FIND "${spline}" "static std::atomic<uint32> splineCounter" atomicSpline)
if(atomicSpline EQUAL -1)
    message(FATAL_ERROR "Worker handoff requires shared movement IDs")
endif()
message(STATUS "PASS: custom script, transport, visibility, AI and phase-order static contracts")

# ManTech bot-session contract: one world-owner pump, no maintenance timer or
# map-owned companion callback also dispatching global handlers.
file(READ "${SOURCE_ROOT}/modules/mod-playerbots/src/playerbot/RandomPlayerbotMgr.cpp" randommgr)
file(READ "${SOURCE_ROOT}/modules/mod-playerbots/src/playerbot/PlayerbotMgr.cpp" botmgr)
file(READ "${SOURCE_ROOT}/src/game/WorldSession.cpp" session)
file(READ "${SOURCE_ROOT}/src/game/WorldSession.h" sessionHeader)
foreach(required "PlayerbotHolder::UpdateAllHolderSessions(diff);")
    string(FIND "${bots}" "${required}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Missing world-owner bot session pump: ${required}")
    endif()
endforeach()
foreach(forbidden "UpdateSessions(elapsed);" "void HandleBotPackets() {}")
    string(FIND "${randommgr}${sessionHeader}" "${forbidden}" found)
    if(NOT found EQUAL -1)
        message(FATAL_ERROR "Legacy bot session path restored: ${forbidden}")
    endif()
endforeach()
foreach(forbidden "sRandomPlayerbotMgr.UpdateSessions(diff);" "mgr->UpdateSessions(diff);")
    string(FIND "${bots}" "${forbidden}" found)
    if(NOT found EQUAL -1)
        message(FATAL_ERROR "Duplicate holder session dispatch: ${forbidden}")
    endif()
endforeach()
foreach(required "void WorldSession::HandleBotPackets()" "ProcessPackets(filter, true);"
    "totalPackets < MaxPacketsPerUpdate" "gameplayInput && !botPackets")
    string(FIND "${session}" "${required}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Missing bounded synthetic packet integration: ${required}")
    endif()
endforeach()
message(STATUS "PASS: single-owner bot session dispatch, packet bounds and player-only latency metrics")
file(READ "${SOURCE_ROOT}/src/mangosd/Master.cpp" master)
string(FIND "${master}" "soapThread.reset();" soapJoin)
string(FIND "${master}" "CharacterDatabase.StopServer();" databaseStop)
if(soapJoin LESS 0 OR databaseStop LESS soapJoin)
    message(FATAL_ERROR "SOAP must join before database shutdown and quick_exit")
endif()

# Background-world port: terrain loading must not replace controlled-unit
# simulation; player-controlled players must never enter the NPC update pass.
foreach(required "EnsureGridLoaded(cell);" "CallForAllControlledUnits" "controlled->IsPlayer()"
    "found.push_back(std::move(explicitUpdates))" "BackgroundWorld::DecideUpdate(helper.ElapsedTime(now)"
    "player->GetSelectionGuid()" "player->GetLootGuid()"
    "object->GetViewPoint().hasViewers()" "creature->IsEscortable()" "creature->GetZoneScript()")
    string(FIND "${map}" "${required}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Missing background-world protection: ${required}")
    endif()
endforeach()
string(FIND "${map}" "discovery.Finish();" discoveryComplete)
string(FIND "${map}" "found.push_back(std::move(explicitUpdates))" directMerge)
if(discoveryComplete EQUAL -1 OR directMerge LESS discoveryComplete)
    message(FATAL_ERROR "Controlled GUIDs must merge after discovery workers finish")
endif()
message(STATUS "PASS: background-world controlled units, timing and discovery-join guards")

# Tile/query lifetime: protect the actual Detour entry points, including callers
# outside PathInfo, rather than relying on the map-owner thread alone.
file(READ "${SOURCE_ROOT}/dep/recastnavigation/Detour/Source/DetourNavMeshQuery.cpp" navquery)
foreach(method findPath findNearestPoly closestPointOnPoly getPolyHeight
    findStraightPath raycast moveAlongSurface findRandomPointAroundCircle
    queryPolygons findDistanceToWall updateSlicedFindPath)
    string(REGEX MATCH "dtNavMeshQuery::${method}\\([^;{}]*\\)[ \t\r\n]*(const[ \t\r\n]*)?\\{[ \t\r\n]*dtAccessGate::Read" guarded "${navquery}")
    if(NOT guarded)
        message(FATAL_ERROR "Navigation query lacks lifetime guard: ${method}")
    endif()
endforeach()
file(READ "${SOURCE_ROOT}/dep/recastnavigation/Detour/Source/DetourNavMesh.cpp" navmesh)
foreach(method addTile removeTile)
    string(REGEX MATCH "dtNavMesh::${method}\\([^;{}]*\\)[ \t\r\n]*\\{[ \t\r\n]*dtAccessGate::Write" guarded "${navmesh}")
    if(NOT guarded)
        message(FATAL_ERROR "Navigation mutation lacks exclusive guard: ${method}")
    endif()
endforeach()
file(READ "${SOURCE_ROOT}/src/game/Maps/GridMap.cpp" terrain)
foreach(method GetHeightStatic GetAreaFlag GetGrid LoadMapAndVMap getLiquidStatus)
    string(REGEX MATCH "TerrainInfo::${method}\\([^;{}]*\\)[ \t\r\n]*(const[ \t\r\n]*)?\\{[ \t\r\n]*dtAccessGate::Read" guarded "${terrain}")
    if(NOT guarded)
        message(FATAL_ERROR "Terrain reader lacks lifetime guard: ${method}")
    endif()
endforeach()
string(FIND "${terrain}" "dtAccessGate::Write terrainLifetime(&m_lifetimeGate)" cleanupGuard)
if(cleanupGuard EQUAL -1)
    message(FATAL_ERROR "Terrain cleanup must exclude async readers")
endif()
file(READ "${SOURCE_ROOT}/src/game/Maps/MoveMap.cpp" movemap)
string(REGEX MATCHALL "tileGuard\\(mmap->tilesLoading_lock\\)" unloadGuards "${movemap}")
list(LENGTH unloadGuards unloadGuardCount)
if(NOT unloadGuardCount EQUAL 2)
    message(FATAL_ERROR "Both tile and whole-map unload must share the loader lock")
endif()
message(STATUS "PASS: navigation readers/writers and terrain cleanup lifetime contracts")

# Whole-map idle AI handoff, never actor-level parallel mutation.
foreach(required "sMapMgr.IdleBotAI().Submit(runIdleBatch, \"idle_bot_map_batch\")" "done.get();"
    "TurtleDiagnostics::OwnerHandoff attribution" "request.stamp.Matches")
    string(FIND "${map}" "${required}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Missing joined idle AI ownership guard: ${required}")
    endif()
endforeach()
foreach(required "CharacterDatabase.ThreadStart();" "CharacterDatabase.ThreadEnd();")
    string(FIND "${manager}" "${required}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Missing idle AI worker database lifetime: ${required}")
    endif()
endforeach()
file(READ "${SOURCE_ROOT}/modules/mod-playerbots/src/playerbot/RandomPlayerbotMgr.cpp" random)
foreach(required "UpdateTeleportPlans()" "WorkSlice slice(TurtleDiagnostics::Micros(), 8192, 2000)"
    "plan.filter.Advance" "GetTransitionGeneration() != plan.generation"
    "pendingTeleportGuids.erase(bot->GetGUIDLow())" "eventCacheGeneration"
    "std::unique_lock<std::mutex> guard(eventCacheMutex)")
    string(FIND "${random}" "${required}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Missing resumable maintenance/lifetime guard: ${required}")
    endif()
endforeach()
string(FIND "${bots}" "sRandomPlayerbotMgr.UpdateTeleportPlans();" planner)
if(planner EQUAL -1)
    message(FATAL_ERROR "Resumable teleport plans must be advanced by the world owner")
endif()
file(READ "${SOURCE_ROOT}/src/game/ObjectMgr.cpp" objectmgr)
string(FIND "${objectmgr}" "AreaEntry::RebuildLookupIndex();" indexed)
if(indexed EQUAL -1)
    message(FATAL_ERROR "Loaded area storage must rebuild the indexed lookup")
endif()
message(STATUS "PASS: idle AI handoff, maintenance resumption, cache lifetime and area index integration")

# Static teleport filters must not accidentally regress into per-bot terrain I/O.
string(FIND "${random}" "if (plan.stage == 1)" filtersStart)
string(FIND "${random}" "if (tlocs.empty())" filtersEnd)
math(EXPR filtersLength "${filtersEnd} - ${filtersStart}")
string(SUBSTRING "${random}" ${filtersStart} ${filtersLength} filters)
foreach(forbidden "sTerrainMgr." "isEnemyHomeZoneFor(" "getAreaFlag(" "GetArea()")
    string(FIND "${filters}" "${forbidden}" found)
    if(NOT found EQUAL -1)
        message(FATAL_ERROR "Runtime teleport filter contains blocking lookup: ${forbidden}")
    endif()
endforeach()
string(FIND "${random}" "PrepareTeleportCache();\n        PrepareTeleportAreaIndex();" prepared)
if(prepared EQUAL -1)
    message(FATAL_ERROR "Teleport classifications must be built after startup source caches")
endif()
foreach(required "typeid(*ai) == typeid(AggressorAI)" "typeid(*ai) == typeid(ReactorAI)"
    "typeid(*ai) == typeid(NullCreatureAI)" "typeid(*ai) == typeid(CritterAI)"
    "!entry.second->CanDeferIdleUpdate()" "info->script_id || !ordinaryAI"
    "ProcessSessionPackets(PACKET_PROCESS_MAP)" "pSession->ProcessPackets(updater, false, 2)")
    string(FIND "${map}" "${required}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Missing idle safety/input checkpoint guard: ${required}")
    endif()
endforeach()
file(READ "${SOURCE_ROOT}/src/game/Spells/SpellAuras.cpp" auras)
foreach(required "!IsPermanent() || !IsPassive() || !IsPositive()" "_heartBeatRandValue || _pveHeartBeatData"
    "typeid(*aura) != typeid(Aura)" "aura->IsPeriodic()" "aura->IsAreaAura() || aura->IsPersistent()")
    string(FIND "${auras}" "${required}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Missing inert-aura safety guard: ${required}")
    endif()
endforeach()
message(STATUS "PASS: precomputed teleport filters, exact AI/inert-aura eligibility, owner-only input checkpoints")

file(READ "${SOURCE_ROOT}/src/game/World.h" worldHeader)
foreach(required "m_tickDiffs.Maximum()" "m_tickDiffs.Current()" "TickDiffWindow<50> m_tickDiffs")
    string(FIND "${worldHeader}" "${required}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Missing measured world timing accessor: ${required}")
    endif()
endforeach()
foreach(required "m_tickDiffs.Record(diff);" "return m_tickDiffs.Average();")
    string(FIND "${world}" "${required}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "World tick timing is not recorded/published: ${required}")
    endif()
endforeach()
message(STATUS "PASS: measured current/maximum/average tick telemetry wiring")

file(READ "${SOURCE_ROOT}/src/game/Objects/Object.cpp" movementObject)
file(READ "${SOURCE_ROOT}/src/game/Objects/Player.cpp" visibilityPlayer)
file(READ "${SOURCE_ROOT}/src/game/Maps/GridNotifiers.cpp" visibilityNotifier)
file(READ "${SOURCE_ROOT}/src/game/Maps/PathFinder.cpp" pathFinder)
file(READ "${SOURCE_ROOT}/src/game/Movement/RandomMovementGenerator.cpp" randomMovement)
foreach(required "m_movementViewers.Snapshot()" "GetMap()->GetPlayer(guid)"
    "viewer->IsInVisibleList(this)" "viewer->GetSession()->SendPacket(&data)")
    string(FIND "${movementObject}" "${required}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Missing NPC movement delivery safety: ${required}")
    endif()
endforeach()
foreach(required "target->AddMovementViewer(GetObjectGuid())" "object->AddMovementViewer(GetObjectGuid())"
    "target->RemoveMovementViewer(GetObjectGuid())" "stealthedUnit->AddMovementViewer(GetObjectGuid())"
    "stealthedUnit->RemoveMovementViewer(GetObjectGuid())" "void Player::ClearVisibleObjects()"
    "guid.IsCreatureOrPet()" "map->GetAnyTypeCreature(guid)")
    string(FIND "${visibilityPlayer}" "${required}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Missing NPC visibility lifecycle hook: ${required}")
    endif()
endforeach()
foreach(required "creature->RemoveMovementViewer(player.GetObjectGuid())" "player.ActivateBroadcastListeners(i_visibleNow)"
    "itr->IsCreatureOrPet()" "player.GetMap()->GetAnyTypeCreature(*itr)")
    string(FIND "${visibilityNotifier}" "${required}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Missing batched visibility lifecycle hook: ${required}")
    endif()
endforeach()
string(FIND "${map}" "player->ClearVisibleObjects();\n    player->ResetMap();" reset)
if(reset EQUAL -1)
    message(FATAL_ERROR "NPC viewer cleanup must precede map removal")
endif()
foreach(required "i_path->ResetForNewRequest()" "i_path->ExcludeSteepSlopes()" "init.Move(i_path.get())")
    string(FIND "${randomMovement}" "${required}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Missing fresh wander request context: ${required}")
    endif()
endforeach()
string(FIND "${pathFinder}" "m_navMesh = m_navMeshQuery ? m_navMeshQuery->getAttachedNavMesh() : nullptr;" reset)
if(reset EQUAL -1)
    message(FATAL_ERROR "Unavailable query must not retain an old navmesh pointer")
endif()
message(STATUS "PASS: NPC viewer lifecycle, normal session hooks, fresh wander/navmesh context wiring")
file(READ "${SOURCE_ROOT}/src/game/Handlers/CharacterHandler.cpp" login)
foreach(required "DelayQueryHolderUnsafePriority" "PLAYER_LOGIN_STAGE" "GetSocket() && holder->GetLoginRequestTime()"
    "traceLogin(\"character_loaded\")" "traceLogin(\"map_and_initial_objects_added\")"
    "traceLogin(\"login_hooks_finished\")")
    string(FIND "${login}" "${required}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Missing human login priority/timing hook: ${required}")
    endif()
endforeach()
message(STATUS "PASS: human priority login and phase timing wiring")

# Upstream integration may compile cleanly while accidentally restoring its
# old scheduler or its unindexed per-login trainer scan.
foreach(required "UpdateDiscoveredCells(now, diff);" "processWorkload().get();" "unitsMvtUpdate.clear();")
    string(FIND "${map}" "${required}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Lost ManTech map ownership/join contract: ${required}")
    endif()
endforeach()
file(READ "${SOURCE_ROOT}/modules/mod-playerbots/src/playerbot/strategy/actions/AutoLearnSpellAction.cpp" training)
string(FIND "${training}" "sCreatureStorage.GetMaxEntry()" fullScan)
string(FIND "${training}" "sObjectMgr.GetBotTrainerEntries(bot->getClass())" indexed)
if(NOT fullScan EQUAL -1 OR indexed EQUAL -1)
    message(FATAL_ERROR "Trainer catch-up must use the class-filtered index")
endif()
file(READ "${SOURCE_ROOT}/src/game/WorldSession.cpp" session)
string(REGEX MATCHALL "void WorldSession::QueuePacket\\(std::unique_ptr" owners "${session}")
list(LENGTH owners ownerCount)
if(NOT ownerCount EQUAL 1)
    message(FATAL_ERROR "Packet ownership overload must have exactly one definition")
endif()
file(READ "${SOURCE_ROOT}/modules/mod-dungeon-clear/src/Ai/Dungeon/DungeonClear/Util/DcLeaderSignal.cpp" gather)
string(FIND "${gather}" "leader->FindMap() != bot->FindMap()" instanceGuard)
if(instanceGuard EQUAL -1)
    message(FATAL_ERROR "Gather signals must stay on the same map owner/instance")
endif()
message(STATUS "PASS: upstream merge preserves map ownership, indexed training and packet lifetime")
file(READ "${SOURCE_ROOT}/CMakeLists.txt" buildConfig)
string(FIND "${buildConfig}" "set(MODULES \"static\" CACHE" enableAll)
string(FIND "${buildConfig}" "set(MODULE_MOD_PLAYERBOTS \"static\" CACHE" enableBots)
if(NOT enableAll EQUAL -1 OR enableBots EQUAL -1)
    message(FATAL_ERROR "Enabling playerbots must not force-enable unrelated optional modules")
endif()
message(STATUS "PASS: playerbot build gate preserves optional-module selection")
file(READ "${SOURCE_ROOT}/src/game/Maps/Map.cpp" aiClockMap)
string(FIND "${aiClockMap}" "player->GetAIElapsed(now)" clockSnapshot)
string(FIND "${aiClockMap}" "auto execute = [this, now](Request const& request, bool minimal)" clockExecute)
string(FIND "${aiClockMap}" "player->ConsumeAIElapsed(now);\n        player->ClearBackgroundAIDueAge();" clockConsume)
if(clockSnapshot LESS 0 OR clockExecute LESS clockSnapshot OR clockConsume LESS clockExecute)
    message(FATAL_ERROR "AI elapsed clock must be snapshotted before admission and consumed in valid execution")
endif()

# Native action predicates and prerequisites must observe current state. A
# generic failure cache keyed only by action/event/target cannot do that.
file(READ "${SOURCE_ROOT}/modules/mod-playerbots/src/playerbot/strategy/Engine.cpp" engine)
file(READ "${SOURCE_ROOT}/modules/mod-playerbots/src/playerbot/strategy/Engine.h" engineHeader)
# CMaNGOS retry adaptation must follow ALL native eligibility checks, not
# resurrect the earlier cache ahead of prerequisites / possible predicates.
string(FIND "${engine}" "bool isPossible = action->isPossible();" possibleIndex)
string(FIND "${engine}" "bool const allowRetry = AllowBackgroundRetry(action, event);" retryIndex)
string(FIND "${engine}" "actionNode->getPrerequisites()" prereqIndex)
if(possibleIndex LESS prereqIndex OR retryIndex LESS possibleIndex)
    message(FATAL_ERROR "Retry admission must follow prerequisites and native isPossible")
endif()
string(FIND "${engine}" "ActionResult Engine::ExecuteAction(" explicitStart)
string(SUBSTRING "${engine}" ${explicitStart} -1 explicitTail)
string(FIND "${explicitTail}" "IsFailureBackedOff" explicitRetry)
if(NOT explicitRetry EQUAL -1)
    message(FATAL_ERROR "Explicit commands must not inherit autonomous retry delays")
endif()
foreach(required "action->isUseful()" "actionNode->getPrerequisites()" "action->isPossible()"
    "ListenAndExecute(action, event)" "actionNode->getAlternatives()" "actionNode->getContinuers()"
    "GetMapWorkGeneration()" "GetTransitionGeneration()")
    string(FIND "${engine}" "${required}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Native action/lifetime contract missing: ${required}")
    endif()
endforeach()
message(STATUS "PASS: native eligibility precedes background retries; explicit actions remain immediate")

# Range growth must register both native dispatch tables, not leave null slots.
file(READ "${SOURCE_ROOT}/src/game/Spells/SpellAuras.cpp" auraSource)
file(READ "${SOURCE_ROOT}/src/game/UnitAuraProcHandler.cpp" procSource)
string(REGEX MATCH "pAuraHandler AuraHandler\\[TOTAL_AURAS\\][^;]+;" auraTable "${auraSource}")
string(REGEX MATCH "pAuraProcHandler AuraProcHandler\\[TOTAL_AURAS\\][^;]+;" procTable "${procSource}")
string(REGEX MATCHALL "&Aura::[A-Za-z0-9_]+" auraEntries "${auraTable}")
string(REGEX MATCHALL "&Unit::[A-Za-z0-9_]+" procEntries "${procTable}")
list(LENGTH auraEntries auraCount)
list(LENGTH procEntries procCount)
if(NOT auraCount EQUAL 231 OR NOT procCount EQUAL 231)
    message(FATAL_ERROR "Every native aura type must have apply/remove and proc dispatch entries")
endif()
file(READ "${SOURCE_ROOT}/src/game/Objects/Unit.cpp" unitSource)
string(FIND "${unitSource}" "HasSpell(46023)" attackerAvoidance)
if(NOT attackerAvoidance EQUAL -1)
    message(FATAL_ERROR "Avoidance must not halve the attacker's outgoing AoE by spell ID")
endif()
message(STATUS "PASS: native custom aura registration and recipient-side Avoidance")
