// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 129, boss 7357 (Mordresh Fire Eye), 31 anchors over 498yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute129_7357()
{
    DungeonClearRouteRegistry::Register(129, DUNGEON_DIFFICULTY_NORMAL, 7357,
        {
            { 2391.42f, 980.99f, 56.02f },
            { 2395.78f, 990.48f, 53.29f },
            { 2392.21f, 1007.87f, 39.80f },
            { 2412.36f, 1009.38f, 38.63f },
            { 2424.30f, 1011.84f, 38.20f },
            { 2441.84f, 1002.82f, 39.25f },
            { 2446.44f, 987.78f, 38.28f },
            { 2461.79f, 973.49f, 37.07f },
            { 2466.99f, 957.07f, 35.00f },
            { 2462.09f, 932.21f, 26.55f },
            { 2465.27f, 917.18f, 27.06f },
            { 2464.11f, 897.14f, 29.05f },
            { 2457.42f, 878.42f, 32.26f },
            { 2452.48f, 871.71f, 34.94f },
            { 2451.66f, 853.66f, 40.02f },
            { 2449.05f, 834.23f, 44.56f },
            { 2445.38f, 813.72f, 44.21f },
            { 2442.60f, 796.85f, 43.48f },
            { 2441.58f, 788.62f, 44.32f },
            { 2453.01f, 773.64f, 45.40f },
            { 2468.97f, 757.56f, 46.72f },
            { 2482.62f, 747.43f, 46.51f },
            { 2506.45f, 753.81f, 40.48f },
            { 2515.82f, 741.34f, 41.96f },
            { 2513.85f, 722.96f, 42.62f },
            { 2507.11f, 707.20f, 48.05f },
            { 2503.39f, 699.15f, 51.53f },
            { 2496.50f, 693.43f, 54.54f },
            { 2482.02f, 684.93f, 54.82f },
            { 2480.72f, 675.11f, 55.05f },
            { 2472.52f, 666.35f, 56.90f },
        });
}
