// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 47, boss 6168 (Roogug), 20 anchors over 316yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute47_6168()
{
    DungeonClearRouteRegistry::Register(47, DUNGEON_DIFFICULTY_NORMAL, 6168,
        {
            { 1943.00f, 1544.63f, 82.00f },
            { 1947.58f, 1561.23f, 82.89f },
            { 1953.45f, 1578.65f, 82.17f },
            { 1956.66f, 1589.24f, 82.65f },
            { 1971.02f, 1597.44f, 82.19f },
            { 1987.14f, 1601.20f, 79.73f },
            { 1994.39f, 1605.05f, 81.56f },
            { 1993.81f, 1625.83f, 82.42f },
            { 2007.30f, 1640.56f, 80.48f },
            { 2022.35f, 1652.76f, 83.05f },
            { 2045.93f, 1643.67f, 83.56f },
            { 2051.81f, 1624.16f, 81.71f },
            { 2058.44f, 1608.00f, 78.53f },
            { 2068.87f, 1593.31f, 78.41f },
            { 2074.10f, 1585.54f, 81.44f },
            { 2083.97f, 1570.93f, 83.06f },
            { 2095.74f, 1557.07f, 82.08f },
            { 2106.08f, 1555.06f, 82.13f },
            { 2122.49f, 1566.94f, 81.28f },
            { 2130.87f, 1574.70f, 82.39f },
        });
}
