// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 90, boss 6235 (Electrocutioner 6000), 41 anchors over 680yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute90_6235()
{
    DungeonClearRouteRegistry::Register(90, DUNGEON_DIFFICULTY_NORMAL, 6235,
        {
            { -452.40f, 117.29f, -209.84f },
            { -461.47f, 114.37f, -209.39f },
            { -477.01f, 120.65f, -210.58f },
            { -496.00f, 126.13f, -209.40f },
            { -493.57f, 144.10f, -208.20f },
            { -482.41f, 161.26f, -207.90f },
            { -469.69f, 174.32f, -207.78f },
            { -461.14f, 178.11f, -207.74f },
            { -452.04f, 177.51f, -208.25f },
            { -447.17f, 197.93f, -207.36f },
            { -445.74f, 217.25f, -207.41f },
            { -446.18f, 235.62f, -207.61f },
            { -452.59f, 254.18f, -207.91f },
            { -471.04f, 262.83f, -207.36f },
            { -487.37f, 269.14f, -207.86f },
            { -495.95f, 276.71f, -210.96f },
            { -514.53f, 284.42f, -210.89f },
            { -527.33f, 295.28f, -211.02f },
            { -533.19f, 306.05f, -215.18f },
            { -535.44f, 326.39f, -221.47f },
            { -535.81f, 343.18f, -227.38f },
            { -536.77f, 360.93f, -230.87f },
            { -533.78f, 380.64f, -231.04f },
            { -526.97f, 397.21f, -230.60f },
            { -515.93f, 411.41f, -230.36f },
            { -503.35f, 424.44f, -230.60f },
            { -490.83f, 436.09f, -230.06f },
            { -482.24f, 456.76f, -230.42f },
            { -480.29f, 465.10f, -230.60f },
            { -468.38f, 482.78f, -230.06f },
            { -464.06f, 498.88f, -230.06f },
            { -466.02f, 519.69f, -230.06f },
            { -475.76f, 535.46f, -230.06f },
            { -488.14f, 549.81f, -229.57f },
            { -491.91f, 568.33f, -230.06f },
            { -495.63f, 578.08f, -230.04f },
            { -518.76f, 581.14f, -230.06f },
            { -528.90f, 577.34f, -227.30f },
            { -532.23f, 568.59f, -223.88f },
            { -537.68f, 550.48f, -218.77f },
            { -542.72f, 533.78f, -216.36f },
        });
}
