// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 816, boss 62038 (Elder Hollowblood), 11 anchors over 133yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute816_62038()
{
    DungeonClearRouteRegistry::Register(816, DUNGEON_DIFFICULTY_NORMAL, 62038,
        {
            { -6305.66f, -4316.22f, 266.17f },
            { -6297.74f, -4312.77f, 266.69f },
            { -6280.56f, -4315.95f, 266.69f },
            { -6263.12f, -4321.13f, 266.68f },
            { -6247.95f, -4328.73f, 266.69f },
            { -6239.87f, -4324.58f, 266.69f },
            { -6231.79f, -4325.91f, 266.69f },
            { -6226.80f, -4332.40f, 266.69f },
            { -6210.49f, -4337.89f, 266.69f },
            { -6190.87f, -4345.06f, 266.36f },
            { -6183.08f, -4348.44f, 266.17f },
        });
}
