// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 70, boss 4854 (Grimlok), 8 anchors over 95yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute70_4854()
{
    DungeonClearRouteRegistry::Register(70, DUNGEON_DIFFICULTY_NORMAL, 4854,
        {
            { 1.92f, 388.08f, -42.70f },
            { 1.80f, 378.87f, -42.72f },
            { 6.60f, 368.39f, -42.03f },
            { 14.33f, 365.77f, -41.49f },
            { 33.71f, 370.71f, -39.92f },
            { 43.11f, 376.68f, -34.99f },
            { 59.37f, 385.35f, -37.69f },
            { 67.45f, 400.74f, -37.69f },
        });
}
