// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 189, boss 61972 (Duke Dreadmoore), 12 anchors over 127yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute189_61972()
{
    DungeonClearRouteRegistry::Register(189, DUNGEON_DIFFICULTY_NORMAL, 61972,
        {
            { 1765.27f, 1122.61f, 8.05f },
            { 1771.58f, 1117.29f, 7.49f },
            { 1789.25f, 1117.22f, 7.56f },
            { 1796.99f, 1120.53f, 7.49f },
            { 1804.05f, 1116.41f, 7.52f },
            { 1806.96f, 1108.66f, 7.30f },
            { 1823.14f, 1106.81f, 5.64f },
            { 1831.72f, 1106.86f, 1.40f },
            { 1840.07f, 1107.22f, -2.66f },
            { 1858.88f, 1107.77f, -3.53f },
            { 1866.85f, 1105.83f, -3.70f },
            { 1873.14f, 1091.12f, -3.70f },
        });
}
