// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 70, boss 6910 (Revelosh), 8 anchors over 106yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute70_6910()
{
    DungeonClearRouteRegistry::Register(70, DUNGEON_DIFFICULTY_NORMAL, 6910,
        {
            { -234.72f, 254.85f, -48.86f },
            { -241.18f, 249.26f, -48.14f },
            { -240.25f, 230.05f, -48.15f },
            { -233.28f, 223.09f, -48.91f },
            { -233.09f, 206.42f, -46.95f },
            { -231.74f, 186.37f, -44.39f },
            { -225.38f, 167.28f, -44.38f },
            { -232.33f, 157.99f, -44.01f },
        });
}
