// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 90, boss 6229 (Crowd Pummeler 9-60), 47 anchors over 722yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute90_6229()
{
    DungeonClearRouteRegistry::Register(90, DUNGEON_DIFFICULTY_NORMAL, 6229,
        {
            { -546.02f, 535.55f, -216.16f },
            { -544.22f, 556.11f, -219.72f },
            { -542.33f, 568.93f, -223.35f },
            { -541.12f, 578.62f, -227.27f },
            { -541.17f, 586.85f, -230.60f },
            { -561.20f, 591.13f, -230.06f },
            { -577.78f, 586.48f, -230.05f },
            { -599.78f, 581.39f, -230.06f },
            { -592.83f, 574.77f, -230.60f },
            { -604.99f, 563.33f, -230.06f },
            { -620.42f, 553.01f, -230.06f },
            { -637.89f, 534.90f, -230.06f },
            { -639.87f, 515.85f, -230.06f },
            { -640.40f, 493.12f, -230.06f },
            { -639.34f, 473.34f, -230.06f },
            { -640.52f, 464.85f, -230.29f },
            { -635.62f, 450.09f, -230.60f },
            { -637.69f, 431.96f, -230.06f },
            { -646.73f, 425.05f, -230.41f },
            { -639.91f, 407.66f, -231.05f },
            { -635.77f, 395.41f, -237.23f },
            { -630.47f, 380.36f, -244.06f },
            { -626.79f, 372.41f, -246.82f },
            { -634.54f, 365.93f, -252.26f },
            { -640.20f, 364.90f, -256.80f },
            { -650.72f, 378.17f, -263.70f },
            { -656.29f, 386.25f, -270.51f },
            { -661.83f, 402.06f, -272.95f },
            { -667.43f, 418.69f, -273.06f },
            { -676.65f, 416.10f, -271.90f },
            { -696.37f, 420.77f, -272.56f },
            { -706.92f, 423.45f, -272.56f },
            { -715.33f, 431.75f, -272.56f },
            { -723.07f, 434.02f, -272.56f },
            { -738.89f, 428.81f, -272.56f },
            { -758.01f, 420.04f, -272.06f },
            { -776.10f, 419.73f, -272.06f },
            { -793.59f, 422.60f, -272.06f },
            { -814.98f, 421.84f, -272.45f },
            { -830.91f, 425.97f, -272.06f },
            { -850.84f, 427.31f, -272.06f },
            { -871.33f, 428.95f, -272.06f },
            { -886.75f, 422.53f, -272.06f },
            { -892.38f, 404.63f, -272.06f },
            { -893.10f, 387.38f, -272.06f },
            { -891.91f, 369.67f, -272.06f },
            { -890.90f, 361.02f, -272.60f },
        });
}
