// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 189, boss 3977 (High Inquisitor Whitemane), 27 anchors over 402yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute189_3977()
{
    DungeonClearRouteRegistry::Register(189, DUNGEON_DIFFICULTY_NORMAL, 3977,
        {
            { 855.68f, 1321.50f, 18.67f },
            { 863.79f, 1321.91f, 18.33f },
            { 872.41f, 1340.19f, 18.01f },
            { 874.96f, 1357.50f, 18.21f },
            { 874.39f, 1377.19f, 18.01f },
            { 874.12f, 1397.78f, 18.01f },
            { 881.92f, 1401.48f, 19.06f },
            { 899.26f, 1393.13f, 18.22f },
            { 919.53f, 1386.71f, 18.42f },
            { 935.76f, 1383.61f, 18.74f },
            { 952.31f, 1380.67f, 18.02f },
            { 972.52f, 1377.05f, 20.86f },
            { 982.25f, 1375.13f, 25.18f },
            { 987.77f, 1368.76f, 26.23f },
            { 1006.16f, 1374.83f, 27.71f },
            { 1016.80f, 1369.82f, 27.49f },
            { 1021.39f, 1379.53f, 28.79f },
            { 1037.91f, 1381.82f, 27.35f },
            { 1052.63f, 1389.09f, 27.30f },
            { 1072.80f, 1394.96f, 30.34f },
            { 1086.69f, 1384.83f, 30.64f },
            { 1103.73f, 1377.02f, 30.31f },
            { 1123.08f, 1375.79f, 30.99f },
            { 1131.38f, 1373.38f, 30.90f },
            { 1142.67f, 1361.74f, 31.00f },
            { 1146.83f, 1369.06f, 32.40f },
            { 1142.28f, 1378.01f, 31.50f },
        });
}
