// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 70, boss 7023 (Obsidian Sentinel), 4 anchors over 43yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute70_7023()
{
    DungeonClearRouteRegistry::Register(70, DUNGEON_DIFFICULTY_NORMAL, 7023,
        {
            { -117.80f, 360.30f, -44.26f },
            { -132.26f, 369.13f, -41.71f },
            { -145.38f, 381.45f, -38.86f },
            { -153.03f, 384.32f, -37.49f },
        });
}
