// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 816, boss 62066 (Cavernweb Broodmother), 15 anchors over 235yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute816_62066()
{
    DungeonClearRouteRegistry::Register(816, DUNGEON_DIFFICULTY_NORMAL, 62066,
        {
            { -6290.13f, -3992.36f, 73.24f },
            { -6284.43f, -3974.50f, 73.19f },
            { -6272.03f, -3963.91f, 73.19f },
            { -6257.47f, -3954.78f, 73.19f },
            { -6241.48f, -3950.37f, 73.19f },
            { -6220.60f, -3948.05f, 73.19f },
            { -6203.76f, -3944.25f, 73.34f },
            { -6194.58f, -3938.24f, 73.45f },
            { -6176.92f, -3939.88f, 73.19f },
            { -6159.45f, -3946.13f, 73.19f },
            { -6143.60f, -3952.25f, 73.20f },
            { -6128.05f, -3959.42f, 73.19f },
            { -6120.25f, -3966.09f, 72.93f },
            { -6100.67f, -3968.11f, 72.66f },
            { -6084.88f, -3973.37f, 72.60f },
        });
}
