// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 70, boss 1325400066 (Altar of Archaedas), 36 anchors over 548yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute70_1325400066()
{
    DungeonClearRouteRegistry::Register(70, DUNGEON_DIFFICULTY_NORMAL, 1325400066,
        {
            { 50.20f, 440.10f, -40.77f },
            { 47.81f, 431.36f, -40.49f },
            { 56.70f, 415.66f, -39.85f },
            { 61.03f, 398.68f, -37.64f },
            { 58.02f, 379.80f, -37.67f },
            { 51.97f, 364.60f, -42.26f },
            { 49.69f, 347.29f, -39.92f },
            { 44.99f, 330.71f, -42.67f },
            { 37.40f, 311.52f, -38.73f },
            { 25.03f, 300.46f, -39.54f },
            { 15.11f, 285.52f, -37.66f },
            { 9.07f, 270.13f, -34.77f },
            { 15.85f, 253.05f, -34.38f },
            { 20.16f, 245.64f, -32.55f },
            { 29.50f, 244.59f, -27.67f },
            { 45.85f, 248.83f, -25.99f },
            { 62.86f, 253.64f, -25.99f },
            { 79.35f, 258.17f, -25.99f },
            { 100.05f, 262.25f, -25.98f },
            { 108.59f, 255.47f, -24.33f },
            { 117.19f, 255.72f, -25.78f },
            { 128.70f, 274.06f, -25.99f },
            { 143.84f, 284.67f, -26.58f },
            { 157.59f, 272.95f, -26.38f },
            { 163.38f, 258.19f, -28.79f },
            { 165.60f, 250.02f, -28.79f },
            { 149.12f, 238.18f, -36.43f },
            { 141.86f, 234.47f, -41.37f },
            { 125.20f, 225.03f, -41.89f },
            { 109.32f, 219.06f, -42.50f },
            { 101.96f, 216.29f, -46.57f },
            { 94.03f, 213.46f, -51.24f },
            { 85.72f, 210.71f, -54.07f },
            { 72.39f, 227.51f, -53.52f },
            { 70.59f, 249.30f, -51.69f },
            { 84.45f, 260.45f, -51.63f },
        });
}
