// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 47, boss 4422 (Agathelos the Raging), 49 anchors over 684yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute47_4422()
{
    DungeonClearRouteRegistry::Register(47, DUNGEON_DIFFICULTY_NORMAL, 4422,
        {
            { 1977.99f, 1829.05f, 82.88f },
            { 1992.95f, 1821.52f, 83.80f },
            { 1994.42f, 1810.38f, 79.42f },
            { 1989.16f, 1803.93f, 78.04f },
            { 1973.26f, 1797.98f, 74.23f },
            { 1966.08f, 1794.26f, 72.05f },
            { 1963.51f, 1786.21f, 70.89f },
            { 1971.41f, 1771.09f, 69.14f },
            { 1979.26f, 1768.88f, 65.61f },
            { 1983.73f, 1775.05f, 61.18f },
            { 1981.66f, 1782.90f, 57.82f },
            { 1978.15f, 1790.47f, 52.99f },
            { 1981.60f, 1807.52f, 50.77f },
            { 1988.94f, 1802.95f, 51.47f },
            { 1990.12f, 1786.55f, 53.52f },
            { 1990.37f, 1769.94f, 56.12f },
            { 1989.26f, 1753.24f, 58.96f },
            { 1988.47f, 1736.38f, 60.63f },
            { 1984.58f, 1718.14f, 60.15f },
            { 1986.17f, 1701.30f, 60.57f },
            { 1988.72f, 1693.03f, 60.75f },
            { 2001.31f, 1682.45f, 65.91f },
            { 2010.12f, 1682.95f, 67.41f },
            { 2022.18f, 1694.36f, 70.14f },
            { 2034.08f, 1706.86f, 73.12f },
            { 2046.77f, 1718.29f, 75.42f },
            { 2059.67f, 1728.70f, 77.86f },
            { 2067.74f, 1745.61f, 77.61f },
            { 2077.37f, 1758.93f, 78.21f },
            { 2088.78f, 1772.30f, 79.04f },
            { 2095.39f, 1787.35f, 75.96f },
            { 2101.13f, 1803.28f, 75.03f },
            { 2106.99f, 1819.36f, 79.90f },
            { 2111.36f, 1837.59f, 78.06f },
            { 2112.12f, 1857.04f, 74.14f },
            { 2114.49f, 1874.05f, 73.05f },
            { 2116.46f, 1882.13f, 71.69f },
            { 2108.79f, 1897.55f, 72.81f },
            { 2097.64f, 1910.46f, 70.75f },
            { 2086.97f, 1924.06f, 66.33f },
            { 2073.52f, 1934.59f, 65.17f },
            { 2066.15f, 1938.42f, 64.50f },
            { 2070.17f, 1945.60f, 63.29f },
            { 2066.60f, 1956.81f, 62.11f },
            { 2072.56f, 1975.80f, 63.22f },
            { 2070.64f, 1987.52f, 64.15f },
            { 2064.13f, 1995.70f, 65.37f },
            { 2069.31f, 2005.32f, 64.30f },
            { 2054.63f, 2016.28f, 62.42f },
        });
}
