// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 47, boss 4424 (Aggem Thorncurse), 46 anchors over 670yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute47_4424()
{
    DungeonClearRouteRegistry::Register(47, DUNGEON_DIFFICULTY_NORMAL, 4424,
        {
            { 2142.09f, 1582.20f, 81.04f },
            { 2125.89f, 1572.14f, 81.79f },
            { 2118.15f, 1569.43f, 81.27f },
            { 2105.92f, 1556.52f, 82.19f },
            { 2096.77f, 1556.03f, 81.91f },
            { 2085.23f, 1568.88f, 82.96f },
            { 2074.24f, 1584.67f, 81.75f },
            { 2063.93f, 1598.72f, 77.23f },
            { 2054.98f, 1613.41f, 79.83f },
            { 2049.11f, 1628.82f, 82.72f },
            { 2045.82f, 1645.32f, 83.73f },
            { 2030.56f, 1652.62f, 82.02f },
            { 2012.04f, 1645.13f, 81.02f },
            { 2002.28f, 1631.76f, 82.19f },
            { 1996.24f, 1616.12f, 84.44f },
            { 1999.88f, 1599.32f, 81.47f },
            { 2003.78f, 1583.31f, 81.87f },
            { 2010.54f, 1565.81f, 82.82f },
            { 2015.45f, 1549.93f, 81.70f },
            { 2023.51f, 1550.62f, 82.03f },
            { 2028.51f, 1544.19f, 80.94f },
            { 2023.32f, 1536.66f, 80.60f },
            { 2026.55f, 1515.28f, 78.52f },
            { 2029.10f, 1498.66f, 73.02f },
            { 2032.28f, 1480.41f, 69.91f },
            { 2040.44f, 1478.89f, 68.97f },
            { 2055.69f, 1467.64f, 67.56f },
            { 2069.22f, 1458.33f, 67.62f },
            { 2079.75f, 1444.84f, 67.37f },
            { 2095.41f, 1440.63f, 65.18f },
            { 2112.62f, 1442.74f, 64.62f },
            { 2120.45f, 1444.91f, 65.21f },
            { 2131.57f, 1461.00f, 67.15f },
            { 2143.50f, 1472.47f, 68.58f },
            { 2155.67f, 1483.99f, 67.94f },
            { 2159.19f, 1494.88f, 69.52f },
            { 2166.20f, 1499.30f, 72.57f },
            { 2176.13f, 1504.15f, 73.53f },
            { 2168.49f, 1512.56f, 68.60f },
            { 2163.60f, 1518.96f, 71.35f },
            { 2155.42f, 1518.63f, 73.27f },
            { 2141.33f, 1508.39f, 73.27f },
            { 2132.16f, 1495.18f, 73.52f },
            { 2121.21f, 1482.37f, 73.03f },
            { 2111.60f, 1469.16f, 73.95f },
            { 2104.35f, 1462.38f, 73.97f },
        });
}
