// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 820, boss 62778 (Ahgk'tos the Pure), 17 anchors over 300yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute820_62778()
{
    DungeonClearRouteRegistry::Register(820, DUNGEON_DIFFICULTY_NORMAL, 62778,
        {
            { -7544.61f, -3578.47f, 150.49f },
            { -7524.30f, -3575.40f, 148.81f },
            { -7507.82f, -3573.00f, 149.18f },
            { -7488.33f, -3567.85f, 149.42f },
            { -7469.10f, -3562.33f, 145.94f },
            { -7449.35f, -3560.26f, 145.82f },
            { -7430.21f, -3555.02f, 145.82f },
            { -7414.69f, -3549.43f, 145.88f },
            { -7396.29f, -3539.10f, 145.82f },
            { -7380.70f, -3531.64f, 145.82f },
            { -7364.11f, -3523.97f, 146.31f },
            { -7344.28f, -3517.31f, 148.16f },
            { -7326.95f, -3510.82f, 146.41f },
            { -7311.15f, -3505.66f, 145.82f },
            { -7294.91f, -3501.49f, 147.75f },
            { -7277.81f, -3498.37f, 149.52f },
            { -7257.23f, -3498.62f, 150.07f },
        });
}
