// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 47, boss 4424 (Aggem Thorncurse), 43 anchors over 648yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute47_4424()
{
    DungeonClearRouteRegistry::Register(47, DUNGEON_DIFFICULTY_NORMAL, 4424,
        {
            { 2133.92f, 1578.75f, 82.44f },
            { 2119.95f, 1565.75f, 80.97f },
            { 2105.96f, 1556.59f, 82.18f },
            { 2096.50f, 1556.37f, 81.87f },
            { 2085.26f, 1568.84f, 82.91f },
            { 2075.63f, 1582.59f, 82.41f },
            { 2066.62f, 1596.09f, 77.80f },
            { 2056.55f, 1611.00f, 79.03f },
            { 2049.37f, 1625.61f, 82.37f },
            { 2048.02f, 1642.22f, 84.22f },
            { 2034.06f, 1651.50f, 82.02f },
            { 2025.85f, 1653.88f, 82.73f },
            { 2011.93f, 1645.07f, 81.02f },
            { 2002.21f, 1631.60f, 82.15f },
            { 1996.15f, 1615.97f, 84.32f },
            { 1999.87f, 1599.37f, 81.53f },
            { 2003.92f, 1582.74f, 81.91f },
            { 2010.80f, 1565.16f, 82.95f },
            { 2015.90f, 1548.45f, 81.48f },
            { 2021.01f, 1532.04f, 80.93f },
            { 2026.82f, 1514.19f, 78.95f },
            { 2029.42f, 1496.51f, 73.25f },
            { 2032.42f, 1488.29f, 70.37f },
            { 2027.84f, 1480.73f, 71.15f },
            { 2039.14f, 1479.91f, 68.66f },
            { 2054.40f, 1467.89f, 68.02f },
            { 2068.53f, 1459.38f, 67.63f },
            { 2079.16f, 1445.15f, 67.33f },
            { 2094.77f, 1440.66f, 65.38f },
            { 2111.15f, 1442.75f, 65.43f },
            { 2119.33f, 1444.13f, 65.41f },
            { 2130.94f, 1460.39f, 67.13f },
            { 2143.02f, 1472.01f, 68.60f },
            { 2155.92f, 1484.22f, 68.17f },
            { 2165.36f, 1498.60f, 72.04f },
            { 2171.32f, 1504.29f, 72.85f },
            { 2166.88f, 1515.20f, 68.60f },
            { 2155.62f, 1515.18f, 72.89f },
            { 2140.88f, 1508.01f, 73.27f },
            { 2130.24f, 1493.11f, 73.52f },
            { 2119.21f, 1480.55f, 73.71f },
            { 2108.56f, 1467.66f, 73.91f },
            { 2103.11f, 1461.22f, 73.97f },
        });
}
