// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 47, boss 4420 (Overlord Ramtusk), 12 anchors over 190yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute47_4420()
{
    DungeonClearRouteRegistry::Register(47, DUNGEON_DIFFICULTY_NORMAL, 4420,
        {
            { 2149.19f, 1446.32f, 76.82f },
            { 2159.23f, 1461.56f, 74.76f },
            { 2166.53f, 1478.13f, 73.58f },
            { 2173.27f, 1495.46f, 73.50f },
            { 2174.33f, 1512.12f, 69.78f },
            { 2175.24f, 1533.12f, 72.24f },
            { 2176.05f, 1549.59f, 72.18f },
            { 2179.25f, 1565.96f, 74.37f },
            { 2185.44f, 1581.57f, 79.26f },
            { 2193.19f, 1596.20f, 80.15f },
            { 2188.22f, 1618.88f, 81.77f },
            { 2195.93f, 1615.65f, 81.62f },
        });
}
