// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 70, boss 7291 (Galgann Firehammer), 10 anchors over 133yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute70_7291()
{
    DungeonClearRouteRegistry::Register(70, DUNGEON_DIFFICULTY_NORMAL, 7291,
        {
            { 44.96f, 432.78f, -40.49f },
            { 55.93f, 416.80f, -40.96f },
            { 61.33f, 401.00f, -38.27f },
            { 60.80f, 384.56f, -38.26f },
            { 53.74f, 378.73f, -38.43f },
            { 34.85f, 375.07f, -40.14f },
            { 19.42f, 366.62f, -40.62f },
            { 9.82f, 364.12f, -42.82f },
            { -0.27f, 377.70f, -43.69f },
            { -3.67f, 385.07f, -43.70f },
        });
}
