// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 816, boss 62037 (Zuluhed the Whacked), 16 anchors over 239yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute816_62037()
{
    DungeonClearRouteRegistry::Register(816, DUNGEON_DIFFICULTY_NORMAL, 62037,
        {
            { -5981.18f, -4207.49f, 322.10f },
            { -5983.15f, -4191.09f, 322.10f },
            { -5983.93f, -4170.22f, 322.10f },
            { -5989.31f, -4153.35f, 322.10f },
            { -5996.26f, -4145.86f, 322.10f },
            { -6017.25f, -4141.97f, 322.10f },
            { -6033.90f, -4145.64f, 322.10f },
            { -6047.10f, -4155.88f, 324.77f },
            { -6054.28f, -4161.09f, 328.48f },
            { -6067.31f, -4171.53f, 329.65f },
            { -6083.64f, -4170.28f, 329.69f },
            { -6098.42f, -4162.81f, 324.97f },
            { -6103.41f, -4146.33f, 322.10f },
            { -6103.37f, -4129.10f, 322.10f },
            { -6103.92f, -4112.34f, 324.16f },
            { -6104.22f, -4103.03f, 324.68f },
        });
}
