// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 90, boss 7079 (Viscous Fallout), 29 anchors over 504yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute90_7079()
{
    DungeonClearRouteRegistry::Register(90, DUNGEON_DIFFICULTY_NORMAL, 7079,
        {
            { -332.22f, -2.28f, -150.86f },
            { -356.54f, 10.02f, -152.31f },
            { -370.90f, 23.44f, -153.36f },
            { -383.06f, 36.62f, -154.53f },
            { -390.82f, 45.07f, -154.78f },
            { -410.37f, 44.58f, -154.08f },
            { -428.76f, 42.49f, -154.13f },
            { -450.09f, 40.51f, -154.52f },
            { -468.51f, 47.19f, -154.12f },
            { -482.00f, 58.49f, -156.26f },
            { -495.27f, 73.06f, -154.25f },
            { -504.73f, 86.72f, -154.16f },
            { -505.84f, 103.97f, -154.03f },
            { -504.57f, 121.54f, -154.74f },
            { -504.33f, 138.16f, -154.53f },
            { -496.69f, 154.71f, -154.16f },
            { -498.56f, 175.03f, -154.26f },
            { -506.32f, 183.43f, -193.71f },
            { -519.91f, 199.84f, -193.16f },
            { -529.44f, 185.94f, -193.16f },
            { -541.79f, 163.93f, -193.16f },
            { -545.66f, 156.17f, -196.74f },
            { -547.91f, 150.28f, -200.78f },
            { -540.05f, 132.39f, -202.27f },
            { -528.79f, 114.48f, -203.93f },
            { -513.43f, 107.26f, -206.95f },
            { -493.31f, 104.87f, -209.30f },
            { -476.47f, 107.57f, -209.78f },
            { -456.92f, 104.27f, -208.92f },
        });
}
