// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 816, boss 62070 (Overlord Blackheart), 30 anchors over 472yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute816_62070()
{
    DungeonClearRouteRegistry::Register(816, DUNGEON_DIFFICULTY_NORMAL, 62070,
        {
            { -6594.58f, -4004.08f, 216.90f },
            { -6593.49f, -4020.86f, 217.66f },
            { -6591.21f, -4038.06f, 219.80f },
            { -6586.85f, -4054.97f, 222.01f },
            { -6581.84f, -4074.18f, 224.47f },
            { -6577.56f, -4090.70f, 226.59f },
            { -6574.01f, -4107.06f, 228.61f },
            { -6569.55f, -4126.28f, 229.54f },
            { -6565.96f, -4146.21f, 229.67f },
            { -6560.85f, -4163.70f, 229.95f },
            { -6551.82f, -4180.06f, 230.53f },
            { -6542.11f, -4196.66f, 231.26f },
            { -6531.55f, -4209.56f, 232.51f },
            { -6519.57f, -4222.61f, 234.06f },
            { -6508.36f, -4236.10f, 235.22f },
            { -6496.85f, -4248.75f, 237.06f },
            { -6480.74f, -4258.00f, 239.90f },
            { -6472.90f, -4260.30f, 244.74f },
            { -6464.89f, -4262.79f, 249.77f },
            { -6456.76f, -4265.30f, 254.78f },
            { -6450.65f, -4271.33f, 258.73f },
            { -6442.84f, -4280.77f, 263.76f },
            { -6425.17f, -4286.06f, 263.65f },
            { -6407.55f, -4289.20f, 263.87f },
            { -6387.11f, -4292.32f, 265.13f },
            { -6371.51f, -4297.71f, 266.09f },
            { -6353.96f, -4303.11f, 266.56f },
            { -6334.10f, -4308.30f, 266.60f },
            { -6318.41f, -4312.58f, 266.17f },
            { -6310.01f, -4314.95f, 266.17f },
        });
}
