// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 820, boss 62779 (Pathun Duskhide), 34 anchors over 538yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute820_62779()
{
    DungeonClearRouteRegistry::Register(820, DUNGEON_DIFFICULTY_NORMAL, 62779,
        {
            { -8025.66f, -3510.34f, 158.10f },
            { -8006.58f, -3510.27f, 158.60f },
            { -7988.81f, -3514.94f, 158.49f },
            { -7981.89f, -3519.62f, 158.70f },
            { -7973.48f, -3540.60f, 158.77f },
            { -7967.18f, -3556.59f, 158.61f },
            { -7957.61f, -3563.56f, 158.78f },
            { -7952.52f, -3573.90f, 159.16f },
            { -7942.71f, -3577.65f, 152.28f },
            { -7932.68f, -3572.36f, 149.14f },
            { -7909.77f, -3567.38f, 146.80f },
            { -7901.15f, -3565.98f, 141.91f },
            { -7882.17f, -3561.55f, 146.06f },
            { -7865.35f, -3554.76f, 147.45f },
            { -7848.88f, -3549.89f, 147.89f },
            { -7832.09f, -3551.50f, 148.01f },
            { -7815.52f, -3556.00f, 149.11f },
            { -7798.02f, -3563.23f, 149.17f },
            { -7781.51f, -3561.17f, 149.28f },
            { -7764.94f, -3559.15f, 148.88f },
            { -7754.46f, -3552.20f, 149.47f },
            { -7735.27f, -3546.82f, 151.69f },
            { -7717.12f, -3537.62f, 152.01f },
            { -7699.87f, -3530.92f, 152.23f },
            { -7692.15f, -3527.52f, 156.11f },
            { -7676.36f, -3532.80f, 154.76f },
            { -7670.54f, -3540.62f, 151.00f },
            { -7648.64f, -3543.92f, 152.20f },
            { -7630.72f, -3541.24f, 151.91f },
            { -7613.05f, -3542.13f, 151.80f },
            { -7592.13f, -3545.39f, 151.20f },
            { -7574.76f, -3553.14f, 150.63f },
            { -7556.36f, -3564.94f, 149.96f },
            { -7550.62f, -3571.00f, 149.90f },
        });
}
