// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 70, boss 7206 (Ancient Stone Keeper), 15 anchors over 224yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute70_7206()
{
    DungeonClearRouteRegistry::Register(70, DUNGEON_DIFFICULTY_NORMAL, 7206,
        {
            { -171.87f, 297.36f, -53.19f },
            { -180.07f, 297.99f, -50.31f },
            { -174.66f, 317.26f, -52.47f },
            { -157.35f, 320.79f, -48.79f },
            { -140.38f, 320.64f, -44.03f },
            { -123.46f, 319.10f, -44.61f },
            { -106.92f, 318.19f, -47.80f },
            { -94.36f, 305.70f, -51.14f },
            { -89.78f, 288.80f, -47.63f },
            { -82.47f, 272.98f, -47.07f },
            { -78.13f, 263.91f, -47.09f },
            { -86.15f, 247.35f, -47.84f },
            { -78.06f, 240.04f, -49.19f },
            { -59.41f, 236.33f, -48.17f },
            { -43.28f, 231.55f, -47.82f },
        });
}
