// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 47, boss 4421 (Charlga Razorflank), 17 anchors over 233yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute47_4421()
{
    DungeonClearRouteRegistry::Register(47, DUNGEON_DIFFICULTY_NORMAL, 4421,
        {
            { 2055.32f, 2014.94f, 62.63f },
            { 2072.36f, 2007.29f, 63.45f },
            { 2086.85f, 1998.87f, 64.03f },
            { 2104.05f, 1988.16f, 65.75f },
            { 2120.09f, 1984.13f, 64.90f },
            { 2131.60f, 1982.01f, 61.10f },
            { 2140.14f, 1983.29f, 60.33f },
            { 2151.17f, 1966.75f, 63.11f },
            { 2160.20f, 1965.52f, 60.11f },
            { 2166.98f, 1960.11f, 58.33f },
            { 2169.90f, 1952.53f, 59.36f },
            { 2161.71f, 1935.19f, 64.58f },
            { 2166.28f, 1919.20f, 68.17f },
            { 2178.28f, 1907.81f, 70.64f },
            { 2186.90f, 1893.51f, 72.31f },
            { 2192.72f, 1876.52f, 75.84f },
            { 2191.74f, 1867.95f, 78.93f },
        });
}
