// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 47, boss 4422 (Agathelos the Raging), 47 anchors over 699yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute47_4422()
{
    DungeonClearRouteRegistry::Register(47, DUNGEON_DIFFICULTY_NORMAL, 4422,
        {
            { 1979.96f, 1827.77f, 83.77f },
            { 1996.66f, 1817.80f, 81.32f },
            { 1992.42f, 1806.51f, 78.75f },
            { 1977.15f, 1799.51f, 75.16f },
            { 1965.98f, 1794.11f, 72.02f },
            { 1963.48f, 1785.93f, 70.90f },
            { 1966.99f, 1775.69f, 70.66f },
            { 1973.30f, 1770.16f, 68.38f },
            { 1982.68f, 1771.18f, 63.34f },
            { 1983.17f, 1779.22f, 59.35f },
            { 1979.06f, 1786.51f, 55.59f },
            { 1978.58f, 1795.27f, 52.28f },
            { 1979.87f, 1803.67f, 50.89f },
            { 1988.61f, 1807.49f, 51.67f },
            { 1990.39f, 1782.73f, 54.24f },
            { 1990.36f, 1766.43f, 56.66f },
            { 1988.80f, 1747.66f, 59.83f },
            { 1986.61f, 1729.04f, 60.43f },
            { 1984.88f, 1711.36f, 60.34f },
            { 1988.23f, 1694.52f, 60.67f },
            { 1995.50f, 1686.13f, 63.93f },
            { 2002.81f, 1682.16f, 66.45f },
            { 2012.06f, 1684.16f, 68.01f },
            { 2025.30f, 1697.97f, 70.60f },
            { 2037.20f, 1710.01f, 73.70f },
            { 2052.13f, 1722.92f, 76.69f },
            { 2063.64f, 1736.02f, 77.30f },
            { 2071.43f, 1751.61f, 78.15f },
            { 2083.82f, 1766.29f, 79.10f },
            { 2093.01f, 1780.91f, 77.50f },
            { 2098.87f, 1796.80f, 75.09f },
            { 2105.11f, 1814.68f, 78.71f },
            { 2111.43f, 1832.76f, 79.29f },
            { 2111.20f, 1849.60f, 75.10f },
            { 2113.28f, 1866.46f, 74.01f },
            { 2112.61f, 1887.17f, 72.85f },
            { 2104.86f, 1902.18f, 71.60f },
            { 2093.99f, 1914.77f, 69.20f },
            { 2088.25f, 1930.76f, 66.28f },
            { 2077.39f, 1945.70f, 64.99f },
            { 2070.15f, 1949.49f, 62.75f },
            { 2066.82f, 1958.02f, 62.32f },
            { 2073.93f, 1980.03f, 63.79f },
            { 2064.41f, 1992.25f, 65.03f },
            { 2059.43f, 2010.41f, 64.20f },
            { 2042.50f, 2010.09f, 62.04f },
            { 2025.88f, 2002.78f, 62.33f },
        });
}
