// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 816, boss 62069 (Halgan Redbrand), 11 anchors over 208yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute816_62069()
{
    DungeonClearRouteRegistry::Register(816, DUNGEON_DIFFICULTY_NORMAL, 62069,
        {
            { -6539.19f, -4206.34f, 231.17f },
            { -6548.46f, -4188.97f, 230.82f },
            { -6561.36f, -4162.07f, 229.90f },
            { -6566.09f, -4142.96f, 229.64f },
            { -6570.10f, -4126.19f, 229.54f },
            { -6574.96f, -4100.96f, 227.90f },
            { -6579.39f, -4083.40f, 225.67f },
            { -6583.92f, -4066.22f, 223.42f },
            { -6589.59f, -4044.00f, 220.59f },
            { -6592.91f, -4024.24f, 218.10f },
            { -6594.80f, -4007.26f, 217.09f },
        });
}
