// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 47, boss 62503 (Rotthorn), 38 anchors over 511yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute47_62503()
{
    DungeonClearRouteRegistry::Register(47, DUNGEON_DIFFICULTY_NORMAL, 62503,
        {
            { 2200.85f, 1621.88f, 84.29f },
            { 2193.10f, 1617.79f, 82.14f },
            { 2179.07f, 1626.82f, 82.22f },
            { 2161.35f, 1631.94f, 82.26f },
            { 2153.31f, 1628.44f, 82.45f },
            { 2140.50f, 1640.87f, 82.60f },
            { 2130.73f, 1657.51f, 82.08f },
            { 2126.54f, 1673.58f, 83.05f },
            { 2125.52f, 1693.08f, 81.27f },
            { 2122.97f, 1700.86f, 80.75f },
            { 2112.45f, 1713.62f, 81.02f },
            { 2102.23f, 1727.57f, 78.75f },
            { 2096.94f, 1733.80f, 78.87f },
            { 2078.24f, 1737.19f, 77.52f },
            { 2063.91f, 1729.60f, 77.53f },
            { 2048.99f, 1719.94f, 75.76f },
            { 2035.47f, 1708.50f, 73.36f },
            { 2024.45f, 1695.97f, 70.43f },
            { 2013.57f, 1683.72f, 66.81f },
            { 2004.50f, 1681.98f, 66.70f },
            { 1989.82f, 1689.53f, 61.56f },
            { 1983.85f, 1695.28f, 60.31f },
            { 1984.40f, 1714.85f, 60.01f },
            { 1983.92f, 1731.30f, 60.27f },
            { 1984.00f, 1749.68f, 58.42f },
            { 1987.04f, 1770.03f, 55.94f },
            { 1987.75f, 1778.36f, 54.63f },
            { 1983.78f, 1777.70f, 60.06f },
            { 1981.51f, 1770.32f, 64.16f },
            { 1973.43f, 1769.70f, 68.21f },
            { 1966.91f, 1775.19f, 70.67f },
            { 1963.51f, 1783.54f, 71.01f },
            { 1964.42f, 1792.04f, 71.49f },
            { 1980.10f, 1799.04f, 75.32f },
            { 1988.99f, 1800.46f, 77.36f },
            { 1996.34f, 1817.41f, 81.12f },
            { 1983.22f, 1826.52f, 83.32f },
            { 1975.87f, 1830.06f, 82.77f },
        });
}
