// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 70, boss 6906 (Baelog), 18 anchors over 233yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute70_6906()
{
    DungeonClearRouteRegistry::Register(70, DUNGEON_DIFFICULTY_NORMAL, 6906,
        {
            { -226.80f, 49.09f, -46.03f },
            { -244.43f, 56.70f, -45.51f },
            { -265.49f, 59.95f, -48.24f },
            { -272.67f, 64.79f, -48.29f },
            { -276.96f, 73.14f, -48.29f },
            { -276.57f, 81.24f, -48.29f },
            { -256.59f, 91.84f, -47.83f },
            { -249.55f, 97.17f, -47.59f },
            { -246.63f, 115.62f, -47.15f },
            { -249.26f, 131.96f, -46.19f },
            { -254.78f, 138.62f, -46.71f },
            { -263.16f, 139.70f, -47.40f },
            { -271.02f, 135.26f, -46.89f },
            { -292.13f, 138.47f, -45.84f },
            { -306.35f, 129.73f, -45.94f },
            { -311.72f, 123.58f, -46.57f },
            { -323.17f, 122.73f, -49.90f },
            { -340.00f, 122.23f, -53.19f },
        });
}
