// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 47, boss 4428 (Death Speaker Jargba), 11 anchors over 161yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute47_4428()
{
    DungeonClearRouteRegistry::Register(47, DUNGEON_DIFFICULTY_NORMAL, 4428,
        {
            { 2107.11f, 1459.79f, 74.14f },
            { 2116.79f, 1477.93f, 73.75f },
            { 2128.09f, 1492.08f, 73.53f },
            { 2140.66f, 1507.94f, 73.35f },
            { 2155.12f, 1514.80f, 73.37f },
            { 2163.02f, 1517.09f, 71.94f },
            { 2173.61f, 1497.82f, 73.51f },
            { 2168.20f, 1481.89f, 73.35f },
            { 2158.56f, 1466.42f, 74.94f },
            { 2152.34f, 1459.91f, 75.94f },
            { 2152.01f, 1447.84f, 76.88f },
        });
}
