// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 129, boss 7358 (Amnennar the Coldbringer), 47 anchors over 774yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute129_7358()
{
    DungeonClearRouteRegistry::Register(129, DUNGEON_DIFFICULTY_NORMAL, 7358,
        {
            { 2592.55f, 1107.50f, 51.29f },
            { 2587.17f, 1090.80f, 53.23f },
            { 2579.87f, 1075.98f, 55.13f },
            { 2564.48f, 1058.56f, 53.54f },
            { 2550.25f, 1049.51f, 49.55f },
            { 2532.22f, 1049.41f, 47.41f },
            { 2513.89f, 1052.69f, 47.45f },
            { 2497.17f, 1056.88f, 48.29f },
            { 2479.93f, 1064.56f, 48.22f },
            { 2464.52f, 1070.81f, 48.26f },
            { 2446.76f, 1078.13f, 44.04f },
            { 2431.09f, 1083.19f, 38.45f },
            { 2420.09f, 1084.67f, 34.91f },
            { 2403.37f, 1084.27f, 32.36f },
            { 2392.58f, 1068.90f, 28.84f },
            { 2382.96f, 1053.18f, 25.49f },
            { 2386.47f, 1045.35f, 24.39f },
            { 2402.69f, 1042.65f, 26.08f },
            { 2418.62f, 1039.50f, 26.19f },
            { 2437.68f, 1032.70f, 25.47f },
            { 2454.96f, 1021.73f, 25.86f },
            { 2462.83f, 1002.65f, 25.54f },
            { 2474.48f, 985.23f, 24.20f },
            { 2469.00f, 978.93f, 25.03f },
            { 2469.42f, 962.00f, 26.45f },
            { 2466.30f, 944.98f, 26.24f },
            { 2463.79f, 944.98f, 32.85f },
            { 2466.76f, 961.17f, 35.36f },
            { 2455.18f, 974.05f, 35.81f },
            { 2448.90f, 990.19f, 37.70f },
            { 2440.33f, 1004.32f, 38.67f },
            { 2428.35f, 1016.01f, 37.56f },
            { 2405.86f, 1008.29f, 38.67f },
            { 2382.87f, 1007.94f, 40.38f },
            { 2367.49f, 1002.37f, 39.51f },
            { 2360.42f, 986.77f, 39.40f },
            { 2368.82f, 972.40f, 44.07f },
            { 2368.05f, 955.71f, 41.31f },
            { 2368.53f, 946.31f, 42.22f },
            { 2375.47f, 939.78f, 43.68f },
            { 2400.53f, 937.37f, 45.00f },
            { 2421.91f, 949.80f, 46.50f },
            { 2425.62f, 968.11f, 47.86f },
            { 2424.27f, 988.02f, 49.81f },
            { 2406.37f, 991.76f, 52.31f },
            { 2397.92f, 990.19f, 53.31f },
            { 2396.63f, 981.32f, 56.53f },
        });
}
