// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 70, boss 7228 (Ironaya), 4 anchors over 51yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute70_7228()
{
    DungeonClearRouteRegistry::Register(70, DUNGEON_DIFFICULTY_NORMAL, 7228,
        {
            { -230.27f, 166.18f, -44.05f },
            { -229.70f, 189.13f, -44.08f },
            { -229.96f, 208.04f, -44.92f },
            { -231.95f, 217.92f, -48.06f },
        });
}
