// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 70, boss 4854 (Grimlok), 9 anchors over 118yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute70_4854()
{
    DungeonClearRouteRegistry::Register(70, DUNGEON_DIFFICULTY_NORMAL, 4854,
        {
            { 10.49f, 395.98f, -43.69f },
            { 2.75f, 389.93f, -43.49f },
            { 1.98f, 373.27f, -42.70f },
            { 7.84f, 367.19f, -41.89f },
            { 25.02f, 369.45f, -39.89f },
            { 42.64f, 376.53f, -36.86f },
            { 60.56f, 386.69f, -37.69f },
            { 60.54f, 404.03f, -37.33f },
            { 58.81f, 412.80f, -38.80f },
        });
}
