// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 816, boss 62068 (Slagfist Destroyer), 29 anchors over 429yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute816_62068()
{
    DungeonClearRouteRegistry::Register(816, DUNGEON_DIFFICULTY_NORMAL, 62068,
        {
            { -6287.02f, -4102.24f, 264.88f },
            { -6292.39f, -4124.13f, 265.53f },
            { -6285.01f, -4143.36f, 265.79f },
            { -6280.47f, -4154.86f, 264.83f },
            { -6286.42f, -4170.53f, 265.79f },
            { -6286.65f, -4187.42f, 265.79f },
            { -6287.81f, -4204.51f, 265.73f },
            { -6287.46f, -4213.21f, 265.66f },
            { -6291.94f, -4220.39f, 265.30f },
            { -6310.46f, -4220.75f, 265.40f },
            { -6320.62f, -4234.75f, 265.71f },
            { -6315.67f, -4251.10f, 265.55f },
            { -6325.83f, -4252.54f, 266.06f },
            { -6330.56f, -4270.59f, 266.57f },
            { -6328.43f, -4287.19f, 266.45f },
            { -6336.07f, -4296.03f, 266.81f },
            { -6353.42f, -4299.73f, 266.60f },
            { -6370.08f, -4296.71f, 266.01f },
            { -6387.17f, -4292.77f, 264.92f },
            { -6406.24f, -4289.73f, 263.88f },
            { -6423.44f, -4285.45f, 263.65f },
            { -6440.25f, -4281.47f, 263.65f },
            { -6451.96f, -4269.98f, 257.89f },
            { -6457.70f, -4264.32f, 254.24f },
            { -6465.69f, -4262.78f, 249.27f },
            { -6473.76f, -4264.21f, 244.20f },
            { -6480.92f, -4268.01f, 238.41f },
            { -6491.60f, -4250.11f, 237.02f },
            { -6507.20f, -4239.09f, 235.42f },
        });
}
