// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 189, boss 4542 (High Inquisitor Fairbanks), 28 anchors over 411yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute189_4542()
{
    DungeonClearRouteRegistry::Register(189, DUNGEON_DIFFICULTY_NORMAL, 4542,
        {
            { 855.68f, 1321.50f, 18.67f },
            { 864.10f, 1321.92f, 18.32f },
            { 871.94f, 1338.81f, 18.01f },
            { 874.86f, 1360.10f, 18.01f },
            { 874.62f, 1377.82f, 18.01f },
            { 876.75f, 1394.94f, 18.07f },
            { 887.45f, 1396.93f, 18.68f },
            { 903.48f, 1391.69f, 18.02f },
            { 919.60f, 1386.56f, 18.07f },
            { 935.52f, 1383.74f, 18.58f },
            { 952.70f, 1380.65f, 18.02f },
            { 971.79f, 1377.20f, 20.50f },
            { 980.10f, 1375.66f, 24.96f },
            { 986.06f, 1370.28f, 25.93f },
            { 1005.47f, 1374.76f, 27.73f },
            { 1023.76f, 1380.37f, 27.39f },
            { 1039.61f, 1385.23f, 27.31f },
            { 1059.25f, 1391.32f, 28.65f },
            { 1076.49f, 1397.70f, 30.54f },
            { 1088.65f, 1384.62f, 30.31f },
            { 1110.26f, 1382.54f, 30.93f },
            { 1118.50f, 1383.85f, 30.87f },
            { 1132.79f, 1374.80f, 30.31f },
            { 1142.00f, 1361.10f, 30.31f },
            { 1143.73f, 1351.49f, 30.31f },
            { 1150.20f, 1345.55f, 30.31f },
            { 1160.39f, 1343.67f, 30.80f },
            { 1162.87f, 1352.06f, 30.89f },
        });
}
