// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 189, boss 4543 (Bloodmage Thalnos), 36 anchors over 481yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute189_4543()
{
    DungeonClearRouteRegistry::Register(189, DUNGEON_DIFFICULTY_NORMAL, 4543,
        {
            { 1688.99f, 1053.48f, 18.68f },
            { 1697.11f, 1054.64f, 19.05f },
            { 1702.79f, 1063.84f, 19.04f },
            { 1703.96f, 1080.59f, 12.75f },
            { 1704.65f, 1088.85f, 8.92f },
            { 1711.64f, 1093.05f, 7.82f },
            { 1728.21f, 1094.11f, 7.32f },
            { 1736.36f, 1094.51f, 7.61f },
            { 1742.24f, 1100.01f, 7.36f },
            { 1757.65f, 1106.40f, 7.75f },
            { 1760.55f, 1121.99f, 8.05f },
            { 1764.94f, 1139.43f, 8.05f },
            { 1777.02f, 1150.97f, 8.30f },
            { 1792.63f, 1164.97f, 7.17f },
            { 1796.79f, 1182.61f, 11.25f },
            { 1796.96f, 1190.96f, 15.43f },
            { 1797.19f, 1200.44f, 18.64f },
            { 1797.68f, 1219.69f, 18.61f },
            { 1797.27f, 1238.12f, 18.35f },
            { 1797.42f, 1255.59f, 18.49f },
            { 1798.45f, 1272.32f, 18.47f },
            { 1799.37f, 1290.12f, 18.74f },
            { 1799.18f, 1306.67f, 18.92f },
            { 1798.96f, 1324.40f, 21.76f },
            { 1798.95f, 1342.38f, 19.49f },
            { 1799.47f, 1358.59f, 19.49f },
            { 1798.52f, 1377.89f, 19.21f },
            { 1798.13f, 1394.45f, 23.65f },
            { 1799.47f, 1412.43f, 16.45f },
            { 1804.82f, 1416.92f, 12.12f },
            { 1810.30f, 1422.89f, 8.74f },
            { 1804.37f, 1431.64f, 9.05f },
            { 1796.26f, 1431.15f, 4.64f },
            { 1788.81f, 1429.16f, 0.33f },
            { 1787.46f, 1419.15f, 0.64f },
            { 1796.13f, 1417.25f, -4.68f },
        });
}
