// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 70, boss 1325400065 (Altar of the Keepers), 26 anchors over 384yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute70_1325400065()
{
    DungeonClearRouteRegistry::Register(70, DUNGEON_DIFFICULTY_NORMAL, 1325400065,
        {
            { -163.76f, 387.99f, -36.44f },
            { -159.69f, 380.38f, -36.92f },
            { -145.06f, 380.49f, -38.85f },
            { -131.40f, 367.65f, -41.53f },
            { -116.76f, 357.78f, -44.42f },
            { -99.68f, 352.90f, -47.96f },
            { -82.40f, 357.29f, -50.19f },
            { -73.62f, 364.90f, -50.16f },
            { -54.61f, 366.39f, -50.01f },
            { -32.27f, 351.19f, -44.07f },
            { -28.07f, 343.96f, -43.97f },
            { -18.59f, 343.61f, -40.03f },
            { -3.41f, 332.28f, -38.84f },
            { 3.91f, 327.39f, -37.92f },
            { 14.36f, 327.75f, -38.61f },
            { 22.34f, 315.66f, -38.75f },
            { 22.39f, 298.58f, -39.31f },
            { 11.62f, 284.73f, -38.13f },
            { 9.44f, 266.64f, -34.87f },
            { 15.83f, 251.32f, -34.36f },
            { 21.49f, 243.34f, -31.98f },
            { 30.03f, 244.40f, -27.48f },
            { 46.08f, 249.82f, -25.99f },
            { 67.78f, 257.69f, -25.99f },
            { 86.41f, 265.03f, -25.90f },
            { 99.79f, 264.31f, -25.99f },
        });
}
