# Port of Classic core policy 61a59c05f. Applied only to ManTechPlayerbots.
# A fetched module update must be reviewed before replacing new security logic.
set(_loot_original "${CMAKE_SOURCE_DIR}/modules/ManTechPlayerbots/playerbot/strategy/actions/SecurityCheckAction.cpp")
file(READ "${_loot_original}" _loot_text)
string(REPLACE "\r\n" "\n" _loot_text "${_loot_text}")
string(SHA256 _loot_hash "${_loot_text}")
if(NOT _loot_hash STREQUAL "658d964d495da859ccf3c6ed1900977b25d3b22474fe30dd371117637b2038b3")
  message(FATAL_ERROR "ManTech SecurityCheckAction changed: review the core loot-policy override before updating its source hash.")
endif()
get_target_property(_loot_sources ${MANTECH_LOOT_POLICY_TARGET} SOURCES)
set(_loot_matches ${_loot_sources})
list(FILTER _loot_matches INCLUDE REGEX "(^|/)SecurityCheckAction\\.cpp$")
list(LENGTH _loot_matches _loot_count)
if(NOT _loot_count EQUAL 1)
  message(FATAL_ERROR "Expected exactly one ManTech SecurityCheckAction for the core loot-policy override.")
endif()
list(REMOVE_ITEM _loot_sources ${_loot_matches})
list(APPEND _loot_sources "${CMAKE_SOURCE_DIR}/src/playerbot_overrides/LootSecurityCheckAction.cpp")
set_property(TARGET ${MANTECH_LOOT_POLICY_TARGET} PROPERTY SOURCES "${_loot_sources}")
message(STATUS "ManTech realm policy: bots remain active under every native loot method")
